demo/urls.py
import django

from django.conf.urls import include, url
from django.contrib import admin
from viewflow import views as viewflow

from .helloworld.flows import HelloWorldFlow
from .shipment.flows import ShipmentFlow
from .customnode.flows import DynamicSplitFlow


if django.VERSION < (1, 7):
    admin.autodiscover()

flow_classes = [HelloWorldFlow, ShipmentFlow, DynamicSplitFlow]


urlpatterns = [
    url(r'^$', viewflow.AllProcessListView.as_view(flow_classes=flow_classes), name="index"),
    url(r'^tasks/$', viewflow.AllTaskListView.as_view(flow_classes=flow_classes), name="tasks"),
    url(r'^queue/$', viewflow.AllQueueListView.as_view(flow_classes=flow_classes), name="queue"),

    # hello world
    url(r'^helloworld/', include([
        HelloWorldFlow.instance.urls,
        url('^$', viewflow.ProcessListView.as_view(), name='index'),
        url('^tasks/$', viewflow.TaskListView.as_view(), name='tasks'),
        url('^queue/$', viewflow.QueueListView.as_view(), name='queue'),
        url('^details/(?P<process_pk>\d+)/$', viewflow.ProcessDetailView.as_view(), name='details'),
        url('^action/cancel/(?P<process_pk>\d+)/$', viewflow.ProcessCancelView.as_view(), name='action_cancel'),
    ], namespace=HelloWorldFlow.instance.namespace), {'flow_cls': HelloWorldFlow}),

    # shipment
    url(r'^shipment/', include([
        ShipmentFlow.instance.urls,
        url('^$', viewflow.ProcessListView.as_view(), name='index'),
        url('^tasks/$', viewflow.TaskListView.as_view(), name='tasks'),
        url('^queue/$', viewflow.QueueListView.as_view(), name='queue'),
        url('^details/(?P<process_pk>\d+)/$', viewflow.ProcessDetailView.as_view(), name='details'),
    ], namespace=ShipmentFlow.instance.namespace), {'flow_cls': ShipmentFlow}),

    # dynamic split
    url(r'^dynamicsplit/', include([
        DynamicSplitFlow.instance.urls,
        url('^$', viewflow.ProcessListView.as_view(), name='index'),
        url('^tasks/$', viewflow.TaskListView.as_view(), name='tasks'),
        url('^queue/$', viewflow.QueueListView.as_view(), name='queue'),
        url('^details/(?P<process_pk>\d+)/$', viewflow.ProcessDetailView.as_view(), name='details'),
    ], namespace=DynamicSplitFlow.instance.namespace), {'flow_cls': DynamicSplitFlow}),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^', include('demo.website')),
]

viewflow/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.template import Template, Context

from .activation import STATUS
from .exceptions import FlowRuntimeError
from .fields import FlowReferenceField, TaskReferenceField, TokenField
from .managers import ProcessManager, TaskManager, coerce_to_related_instance


class AbstractProcess(models.Model):
    """
    Base class for Process data object
    """
    flow_cls = FlowReferenceField()
    status = models.CharField(max_length=50, default=STATUS.NEW)

    created = models.DateTimeField(auto_now_add=True)
    finished = models.DateTimeField(blank=True, null=True)

    objects = ProcessManager()

    @property
    def created_by(self):
        return self.flow_cls.task_cls._default_manager \
            .get(process=self, flow_task_type='START').owner

    def active_tasks(self):
        return self.flow_cls.task_cls._default_manager \
            .filter(process=self, finished__isnull=True) \
            .order_by('created')

    def get_task(self, flow_task, status=None):
        """
        Return task instance
        """
        if status is None:
            status = [STATUS.NEW, STATUS.ASSIGNED, STATUS.STARTED]
        elif not isinstance(status, (list, tuple)):
            status = [status]

        return self.flow_cls.task_cls._default_manager.get(
            process=self, flow_task=flow_task, status__in=status)

    def summary(self):
        """
        Quick textual process state representation for end user
        """
        if self.flow_cls and self.flow_cls.process_cls == type(self):
            return Template(self.flow_cls.summary_template).render(Context({'process': self, 'flow_cls': self.flow_cls}))

        return "{} - {}".format(self.flow_cls.process_title, self.status)

    def __str__(self):
        if self.flow_cls:
            return '{} #{}'.format(self.flow_cls.process_title, self.pk)
        return "<Process {}> - {}".format(self.pk, self.status)

    def refresh_from_db(self, using=None, fields=None, **kwargs):
        if hasattr(models.Model, 'refresh_from_db'):
            super(AbstractProcess, self).refresh_from_db(using=using, fields=fields, **kwargs)
        else:
            """
            django 1.6, only basic fallback
            """
            db_instance = self.__class__._default_manager.filter(pk=self.pk).get()
            for field in self._meta.concrete_fields:
                setattr(self, field.attname, getattr(db_instance, field.attname))

    class Meta:
        abstract = True

    def get_absolute_url(self):
        return reverse(
            '{}:details'.format(self.flow_cls.instance.namespace),
            kwargs={'process_pk': self.pk}
        )


class AbstractTask(models.Model):
    """
    Base class for Task state objects.

    In addition, you have to define at least process foreign key field::

        process = models.ForeignKey(Process)

    """
    flow_task = TaskReferenceField()
    flow_task_type = models.CharField(max_length=50)
    status = models.CharField(max_length=50, default=STATUS.NEW, db_index=True)

    created = models.DateTimeField(auto_now_add=True)
    started = models.DateTimeField(blank=True, null=True)
    finished = models.DateTimeField(blank=True, null=True)
    previous = models.ManyToManyField('self', symmetrical=False, related_name='leading')
    token = TokenField(default='start')

    objects = TaskManager()

    @property
    def flow_process(self):
        """
        Returns process instance of flow_cls type
        """
        if self.flow_task is not None:
            return coerce_to_related_instance(self.process, self.flow_task.flow_cls.process_cls)

    def summary(self):
        """
        Quick textual task result representation for end user
        """
        if self.flow_task:
            if self.finished:
                if hasattr(self.flow_task, 'task_result_summary'):
                    return Template(self.flow_task.task_result_summary or "").render(Context({
                        'process': self.flow_process,
                        'task': self,
                        'flow_cls': self.flow_task.flow_cls,
                        'flow_task': self.flow_task}))
            else:
                if hasattr(self.flow_task, 'task_description'):
                    return self.flow_task.task_description or ""

        return ""

    def save(self, *args, **kwargs):
        if self.status == STATUS.PREPARED:
            raise FlowRuntimeError("Can't save task with intermediate status - PREPARED")

        if self.flow_task:
            self.flow_task_type = self.flow_task.task_type

        super(AbstractTask, self).save(*args, **kwargs)

    def activate(self):
        """
        Instantiate and configure new task activation
        """
        activation = self.flow_task.activation_cls()
        activation.initialize(self.flow_task, self)
        return activation

    def __str__(self):
        if self.flow_task:
            return "<{}.{}/{}> - {}".format(
                self.flow_task.flow_cls._meta.namespace,
                self.flow_task,
                self.pk,
                self.status)
        return "<Task {}> - {}".format(self.pk, self.status)

    def refresh_from_db(self, using=None, fields=None, **kwargs):
        if hasattr(models.Model, 'refresh_from_db'):
            super(AbstractTask, self).refresh_from_db(using=using, fields=fields, **kwargs)
        else:
            """
            django 1.6, only basic fallback
            """
            db_instance = self.__class__._default_manager.filter(pk=self.pk).get()
            for field in self._meta.concrete_fields:
                setattr(self, field.attname, getattr(db_instance, field.attname))

    def get_absolute_url(self, user=None):
        if user:
            return self.flow_task.get_task_url(self, url_type='details', user=user)
        return self.flow_task.get_task_url(self, url_type='details')

    class Meta:
        abstract = True


class Process(AbstractProcess):
    class Meta:
        verbose_name_plural = 'Process list'


class Task(AbstractTask):
    process = models.ForeignKey(Process)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, db_index=True)
    external_task_id = models.CharField(max_length=50, blank=True, null=True, db_index=True)
    owner_permission = models.CharField(max_length=255, blank=True, null=True)

    comments = models.TextField(blank=True, null=True)

viewflow/forms.py
from django import forms
from viewflow.models import Task


class ActivationDataForm(forms.ModelForm):
    started = forms.DateTimeField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('prefix', '_viewflow_activation')
        super(ActivationDataForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = ['started']

viewflow/flow/views/actions.py
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from .base import (
    FlowManagePermissionMixin, BaseTaskActionView, get_task_hyperlink
)


class UndoView(FlowManagePermissionMixin, BaseTaskActionView):
    action_name = 'undo'

    def can_proceed(self):
        return self.activation.undo.can_proceed()

    def perform(self):
        self.activation.undo()
        hyperlink = get_task_hyperlink(self.activation.task, self.request.user)
        msg = _('Task {hyperlink} has been undone.').format(hyperlink=hyperlink)
        messages.info(self.request, mark_safe(msg), fail_silently=True)


class CancelView(FlowManagePermissionMixin, BaseTaskActionView):
    action_name = 'cancel'

    def can_proceed(self):
        return self.activation.cancel.can_proceed()

    def perform(self):
        self.activation.cancel()
        hyperlink = get_task_hyperlink(self.activation.task, self.request.user)
        msg = _('Task {hyperlink} has been canceled.').format(hyperlink=hyperlink)
        messages.info(self.request, mark_safe(msg), fail_silently=True)


class PerformView(FlowManagePermissionMixin, BaseTaskActionView):
    """Non-interactive task that cancelled and need to be started manually."""

    action_name = 'execute'

    def can_proceed(self):
        return self.activation.perform.can_proceed()

    def perform(self):
        self.activation.perform()
        hyperlink = get_task_hyperlink(self.activation.task, self.request.user)
        msg = _('Task {hyperlink} has been executed.').format(hyperlink=hyperlink)
        messages.success(self.request, mark_safe(msg), fail_silently=True)


class ActivateNextView(FlowManagePermissionMixin, BaseTaskActionView):
    """Activate next task without interactive task redone."""

    action_name = 'activate_next'

    def can_proceed(self):
        return self.activation.activate_next.can_proceed()

    def perform(self):
        self.activation.activate_next()

viewflow/flow/views/base.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views import generic

from ... import activation
from ...decorators import flow_view


def get_next_task_url(request, process):
    """Heuristic for user on complete task redirect."""
    if '_continue' in request.POST:
        # Try to find next task available for the user
        task_cls = process.flow_cls.task_cls

        user_tasks = task_cls._default_manager \
            .filter(process=process, owner=request.user, status=activation.STATUS.ASSIGNED)

        if user_tasks.exists():
            task = user_tasks.first()
            return task.flow_task.get_task_url(task, url_type='guess', user=request.user)
        else:
            user_tasks = task_cls._default_manager.user_queue(request.user)\
                .filter(process=process, status=activation.STATUS.NEW)
            if user_tasks.exists():
                task = user_tasks.first()
                return task.flow_task.get_task_url(task, url_type='guess', user=request.user)

    elif 'back' in request.GET:
        # Back to task list
        back_url = request.GET['back']
        if not is_safe_url(url=back_url, host=request.get_host()):
            back_url = '/'
        return back_url

    # Back to process list
    if process and process.pk:
        return reverse('{}:details'.format(process.flow_cls.instance.namespace),
                       kwargs={'process_pk': process.pk})
    else:
        return reverse('{}:index'.format(process.flow_cls.instance.namespace))


def get_process_hyperlink(process):
    """
    Return process url wrapped in a html hyperlink tag.

    :param process: Process
    :type process: viewflow.models.AbstractProcess
    :rtype: str
    """
    return '<a href="{process_url}">#{process_pk}</a>'.format(
        process_url=process.get_absolute_url(),
        process_pk=process.pk
    )


def get_task_hyperlink(task, user=None):
    """
    Return task url wrapped in a html hyperlink tag.

    :param task: Task
    :type task: viewflow.models.AbstractTask
    :rtype: str
    """
    return '<a href="{task_url}">#{task_pk}</a>'.format(
        task_url=task.get_absolute_url(user),
        task_pk=task.pk
    )


class FlowViewPermissionMixin(object):
    flow_cls = None

    def dispatch(self, *args, **kwargs):
        self.flow_cls = kwargs.get('flow_cls', self.flow_cls)
        return permission_required(self.flow_cls.instance.view_permission_name)(
            super(FlowViewPermissionMixin, self).dispatch)(*args, **kwargs)


class FlowManagePermissionMixin(object):
    flow_cls = None

    def dispatch(self, *args, **kwargs):
        self.flow_cls = kwargs.get('flow_cls', self.flow_cls)
        return permission_required(self.flow_cls.instance.manage_permission_name)(
            super(FlowManagePermissionMixin, self).dispatch)(*args, **kwargs)


class DetailsView(generic.TemplateView):

    """
    Default details view for flow task.

    Get confirmation from user, assigns task and redirects to task pages.
    """

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_cls._meta

        return (
            '{}/{}/{}_details.html'.format(opts.app_label, opts.flow_label, flow_task.name),
            '{}/{}/task_details.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/task_details.html')

    def get_context_data(self, **kwargs):
        context = super(DetailsView, self).get_context_data(**kwargs)
        context['activation'] = self.activation
        return context

    @flow_view()
    def dispatch(self, request, activation, *args, **kwargs):
        self.activation = activation

        if not self.activation.flow_task.can_view(request.user, self.activation.task):
            raise PermissionDenied
        return super(DetailsView, self).dispatch(request, *args, **kwargs)


class BaseTaskActionView(generic.TemplateView):
    flow_cls = None
    action_name = None

    def can_proceed(self):
        raise NotImplementedError

    def perform(self):
        raise NotImplementedError

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_cls._meta

        return (
            '{}/{}/{}_{}.html'.format(opts.app_label, opts.flow_label, flow_task.name, self.action_name),
            '{}/{}/task_{}.html'.format(opts.app_label, opts.flow_label, self.action_name),
            'viewflow/flow/task_{}.html'.format(self.action_name),
            'viewflow/flow/task_action.html')

    def get_success_url(self):
        return self.activation.flow_task.get_task_url(self.activation.task, 'details', user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(BaseTaskActionView, self).get_context_data(**kwargs)
        context['activation'] = self.activation
        context['flow_cls'] = self.flow_cls
        return context

    def post(self, request, *args, **kwargs):
        if 'run_action' in request.POST:
            self.perform()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(request, *args, **kwargs)

    @flow_view()
    def dispatch(self, request, activation, **kwargs):
        self.flow_cls = activation.flow_cls
        self.activation = activation

        if not self.can_proceed():
            hyperlink = get_task_hyperlink(self.activation.task, self.request.user)
            msg = _("Task {hyperlink} Can't execute action {action}.") \
                .format(hyperlink=hyperlink, action=self.action_name.title)
            messages.error(request, mark_safe(msg), fail_silently=True)

            return redirect(activation.flow_task.get_task_url(activation.task, url_type='details', user=request.user))

        return super(BaseTaskActionView, self).dispatch(request, **kwargs)

viewflow/templates/viewflow/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Viewflow{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</html>

viewflow/templates/viewflow/site_index.html
{% extends 'viewflow/base.html' %}
{% load viewflow %}

{% block title %}{{ block.super}} | All processes{% endblock %}

{% block content %}
<div>
    <h1>All processes list</h1>
</div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Process</th>
        <th>Started</th>
        <th>Finished</th>
        <th>Active Tasks</th>
    </thead>
    <tbody>
        {% for process in process_list %}
        <tr>
            <td><a href="{% flowurl process 'details' %}">{{ process.id }}</a></td>
            <td>{{ process.flow_cls.process_title }}</td>
            <td>{{ process.created }}</td>
            <td>{{ process.finished|default:"" }}</td>
            <td>
                {% for task in process.active_tasks %}
                {% flowurl task user=request.user as task_url %}
                {% if task_url %}
                <a href="{{ task_url }}?back={{ request.get_full_path|urlencode }}">
                    {{ task.flow_task }}
                </a>
                {% else %}
                    {{ task.flow_task }}
                {% endif %}
                {% endfor %}
            </td>

        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No process yet</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

viewflow/templates/viewflow/site_queue.html
{% extends 'viewflow/base.html' %}
{% load viewflow %}

{% block title %}{{ block.super}} | All tasks{% endblock %}

{% block content %}
<div>
    <h1>All Queues</h1>
</div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Process</th>
        <th>Name</th>
        <th class="span1">Started</th>
        <th class="span1">Finished</th>
        <th>Status</th>
    </thead>
    <tbody>
        {% for task in queue %}
        <tr>
            <td><a href="{% flowurl task user=request.user %}">{{ task.process.id }}/{{ task.id }}</a></td>
            <td><a href="{% flowurl task.process 'details' %}">{{ task.process.id }}</a></td>
            <td>{{ task.flow_task }}</td>
            <td>{{ task.created }}</td>
            <td>{{ task.finished|default:"" }}</td>
            <td>{{ task.get_status_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

viewflow/templates/viewflow/site_tasks.html
{% extends 'viewflow/base.html' %}
{% load viewflow %}

{% block title %}{{ block.super}} | All tasks{% endblock %}

{% block content %}
<div>
    <h1>All tasks list</h1>
</div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Process</th>
        <th>Task</th>
        <th>Description</th>
        <th class="span1">Summary</th>
        <th class="span1">Assigned</th>
    </thead>
    <tbody>
        {% for task in task_list %}
        <tr>
            <td><a href="{% flowurl task user=request.user %}">{{ task.process.id }}/{{ task.id }}</a></td>
            <td><a href="{% flowurl task.process 'details' %}">{{ task.flow_task.flow_cls.process_title }}</a></td>
            <td>{{ task.flow_task }}</td>
            <td>{{ task.summary }}</td>
            <td>{{ task.flow_process.summary }}</td>
            <td>{{ task.created }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}